version: "2"
services:
    app:
        build:
            context: ./dockerfiles
            dockerfile: dockerfile
        container-name: node-container
        restart: always
        ports:
          - "7777:8080"
          - "80:80"
          - "5555:443"
        volumes:
          - "./www:var/www/html"
        depends_on:
          - postgres-database  
    postgres-database:
        container_name: postgres-database
        image: postgres:11
        restart: unless-stopped
        volumes:
          - ./:/data
        environment: 
          POSTGRES_DB: pgsql
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpgsql       