version: "2"
services:
  clinical:
    build:
        context: ./clinicloud
        dockerfile: dockerfile
    command: yarn start
    image: soft82/cliserver
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - "./clinicloud:/usr/app"
    depends_on:
      - pg-database
  clinical-web:
    build:
        context: ./clinicloud-web
        dockerfile: dockerfile
    # command: npm start
    image: soft82/clinicloud-web
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./clinicloud-web:/usr/src/app"
    depends_on:
      - pg-database
    stdin_open: true  
  pg-database:
    container_name: pg-database
    image: postgres:11
    restart: unless-stopped
    volumes:
      - ./:/data
    environment: 
      POSTGRES_DB: pgsql
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpgsql       